<?php

namespace AppBundle\Repository;

/**
 * ThoughtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThoughtsRepository extends \Doctrine\ORM\EntityRepository
{
}
